### PR TITLE
pc - update README.md in frontend directory

### PR DESCRIPTION
**Pull request by pconrad**
# Overview

The `frontend` directory has it's own `README.md` file; before this PR it was  mostly boilerplate from the Create React App script.   

It now has just the content that is directly applicable, and a list of files/directories with description of each.

### CODE REVIEW

**Review by andrewhlu — CHANGES_REQUESTED** [review]
It looks like you mistakenly updated the README in the root directory instead of in the frontend directory. Mind fixing this?

**Comment by pconrad** [comment]
> It looks like you mistakenly updated the README in the root directory instead of in the frontend directory. Mind fixing this?

Good catch... will do.

**Comment by pconrad** [comment]
> > It looks like you mistakenly updated the README in the root directory instead of in the frontend directory. Mind fixing this?
> 
> Good catch... will do.

Done... please re-review

**Review by andrewhlu — APPROVED** [review]
LGTM!

**Pull request merged**
